In [ ]:
import os
actors = os.listdir('data')

In [ ]:
os.listdir(os.path.join('data',actors[0]))

In [5]:
filenames=[]
for actor in actors:
    for file in os.listdir(os.path.join('data',actor)):
        filenames.append(os.path.join('data',actor,file))

In [6]:
filenames[0]

'data/Aamir_Khan/Aamir.100.jpg'

In [7]:
import pickle

pickle.dump(filenames, open('filenames.pkl','wb'))

In [1]:
from tensorflow.keras.preprocessing import image
from keras_vggface.utils import preprocess_input
from keras_vggface.vggface import VGGFace
# from deepface.model.facial_recognition import VGGFace
import numpy as np
import pickle
import tensorflow as tf
import tqdm

2025-11-27 08:10:20.282662: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
filename = pickle.load(open('filenames.pkl','rb'))

In [2]:
model = VGGFace(model='resnet50', include_top=False, input_shape=(224,224,3), pooling='avg')

I0000 00:00:1764231029.066965    7282 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2242 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5


In [3]:
def feature_extractor(img_path, model):
    img = image.load_img(img_path, target_size= (224,224))
    img_arr = image.img_to_array(img)
    expand_img = np.expand_dims(img_arr, axis=0)
    process_img = preprocess_input(expand_img)
    result = model.predict(process_img)
    flat_pred = result.flatten()
    return flat_pred

In [ ]:
features = []
for file in tqdm(filenames):
    features.append(feature_extractor(file, model))

pickle.dump(features, open('features.pkl','wb'))

In [8]:
%run feature_extractor.py

2025-11-27 08:34:16.045638: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1764232462.275124    8099 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2242 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
  0%|                                                                                          | 0/8664 [00:01<?, ?it/s]


AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'

In [9]:
exit()

In [13]:
# from deepface import DeepFace
from tensorflow.keras.layers import GlobalMaxPool2D

In [1]:
from deepface import DeepFace

2025-11-27 10:23:42.352238: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
result_emb = DeepFace.represent(img_path='data/Aamir_Khan/Aamir.100.jpg', model_name = 'VGG-Face')

2025-11-27 10:24:00.402717: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1764239040.402829    9123 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2242 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5


25-11-27 10:24:01 - 🔗 vgg_face_weights.h5 will be downloaded from https://github.com/serengil/deepface_models/releases/download/v1.0/vgg_face_weights.h5 to /home/huzefa_m/.deepface/weights/vgg_face_weights.h5...


Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/vgg_face_weights.h5
To: /home/huzefa_m/.deepface/weights/vgg_face_weights.h5
100%|████████████████████████████████████████████████████████████████████████████████| 580M/580M [02:26<00:00, 3.95MB/s]
2025-11-27 10:26:38.078526: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 411041792 exceeds 10% of free system memory.
2025-11-27 10:27:20.433504: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91600
2025-11-27 10:27:30.365499: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.06GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2025-11-27 10:27:30.620101: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:382] Garbage collection: deallocate free memo

In [47]:
import numpy as np
result_arr = np.array(result_emb[0]['embedding'])

In [61]:
layer = GlobalMaxPool2D()(expand_result)

In [69]:
layer.shape

TensorShape([2, 1024])

In [70]:
layer_numpy = layer.numpy()

In [71]:
layer_numpy

array([[0.        , 0.        , 0.        , ..., 0.03405961, 0.        ,
        0.00798661],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(2, 1024), dtype=float32)

In [72]:
flat_layer = layer_numpy.flatten()

In [73]:
flat_layer.shape

(2048,)

In [67]:
from tensorflow.keras.layers import Flatten

flat_layer = Flatten()(layer)

In [68]:
flat_layer.shape

TensorShape([2, 1024])

In [58]:
# h,w,c = 7,7,256
result_arr_4d = result_arr.reshape(2,2,1024)

In [59]:
expand_result = np.expand_dims(result_arr_4d,1)

In [60]:
expand_result.shape

(2, 1, 2, 1024)

In [45]:
ex_expand_result = np.expand_dims(expand_result,0)

In [46]:
ex_expand_result.shape

(1, 1, 8, 8, 64)

In [30]:
e_ex_expand_result = np.expand_dims(ex_expand_result,1)

In [31]:
e_ex_expand_result.shape

(4096, 1, 1, 1)

In [44]:
layer.shape

TensorShape([1, 64])

In [36]:
layer1 = GlobalMaxPool2D()(layer)

ValueError: Input 0 of layer "global_max_pooling2d_6" is incompatible with the layer: expected ndim=4, found ndim=2. Full shape received: (4096, 1)

In [75]:
def extract_features(img_paths):
    deepfaced = DeepFace.represent(img_path=img_paths, model_name='VGG-Face')
    into_arr = np.array(deepfaced[0]['embedding'])
    into_arr_4d = into_arr.reshape(2,2,1024)
    ex_into_arr_4d = np.expand_dims(into_arr_4d,1)
    layer = GlobalMaxPool2D()(ex_into_arr_4d)
    layer_numpy = layer.numpy()
    flat_layer = layer_numpy.flatten()
    norm_layer = flat_layer/norm(flat_layer)
    return norm_layer

In [79]:
from numpy.linalg import norm
feature.append(extract_features('data/Aamir_Khan/Aamir.100.jpg'))

In [78]:
feature = []

In [81]:
feature.shape

AttributeError: 'list' object has no attribute 'shape'

In [84]:
import pickle

embed = pickle.load(open('/mnt/e/AI-ML course/Fashion Recommender System/embeddings.pkl', 'rb'))

In [86]:
embed.shape

AttributeError: 'list' object has no attribute 'shape'

In [87]:
filenames = pickle.load(open('filenames.pkl', 'rb'))

In [89]:
pickle.dump(feature, open('features.pkl', 'wb')

In [1]:
%run feature_extractor1.py

2025-11-27 13:01:26.621603: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
  0%|                                                                                          | 0/8664 [00:00<?, ?it/s]2025-11-27 13:01:51.051077: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1764248511.051171   11860 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2242 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
2025-11-27 13:02:05.199356: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 411041792 

In [2]:
exit()

In [1]:
%run test.py

2025-11-27 14:31:35.489919: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-27 14:32:26.964286: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1764253946.964487   12807 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2242 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
2025-11-27 14:38:39.244239: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 411041792 exceeds 10% of free system memory.
2025-11-27 14:39:48.580488: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc

[0.         0.00042058 0.         ... 0.         0.         0.01932298]


In [2]:
exit()

# Now Testing

In [164]:
import pickle
import os
import cv2
from mtcnn import MTCNN
import numpy as np
import tensorflow as tf
from sklearn.metrics.pairwise import cosine_similarity
from deepface import DeepFace
from tensorflow.keras.layers import GlobalMaxPool2D
from numpy.linalg import norm
from tensorflow.keras.preprocessing import image

In [165]:
feature_list = pickle.load(open('features.pkl', 'rb'))
filenames = pickle.load(open('filenames.pkl', 'rb'))

In [166]:
def extract_features(img_paths):
    deepfaced = DeepFace.represent(img_path=img_paths, model_name='VGG-Face', enforce_detection=False)
    into_arr = np.array(deepfaced[0]['embedding'])
    into_arr_4d = into_arr.reshape(2,2,1024)
    ex_into_arr_4d = np.expand_dims(into_arr_4d,1)
    layer = GlobalMaxPool2D()(ex_into_arr_4d)
    layer_numpy = layer.numpy()
    flat_layer = layer_numpy.flatten()
    norm_layer = flat_layer/norm(flat_layer)
    return norm_layer

In [65]:
img_loc = 'sample/ranbir_kapoor_dup.jpg'
sample_img = extract_features(img_loc)
print(sample_img)

[0.         0.0004206  0.         ... 0.         0.         0.01932297]


In [70]:
sample_img.shape

(2048,)

In [71]:
type(sample_img)

numpy.ndarray

In [72]:
sample_img.reshape(1,-1)

array([[0.        , 0.        , 0.        , ..., 0.00723872, 0.        ,
        0.        ]], shape=(1, 2048), dtype=float32)

In [13]:
feature_list[0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(2048,), dtype=float32)

In [73]:
s1 = cosine_similarity(sample_img.reshape(1,-1),feature_list[0].reshape(1,-1))[0][0]

In [25]:
s2 = cosine_similarity(sample_img.reshape(1,-1),feature_list[1].reshape(1,-1))[0][0]

In [28]:
similarity.append(s1)

In [51]:
similarity

[]

In [30]:
similarity.append(s2)

In [34]:
similarity.sort

<function list.sort(*, key=None, reverse=False)>

In [184]:
similarity =[]

In [185]:
for i, arr in enumerate(feature_list):
    simi = cosine_similarity(sample_img.reshape(1,-1),arr.reshape(1,-1))[0][0]
    similarity.append(simi)

In [189]:
similarity1 = similarity

In [186]:
index_of_max = similarity.index(max(similarity))

In [187]:
filenames[index_of_max]

'data/Anushka_Shetty/Anushka_Shetty.245.jpg'

In [188]:
float(f"{(float(max(similarity))*100):.2f}")

56.9

In [191]:
index_pos  = sorted(list(enumerate(similarity1)),reverse=True, key=lambda x:x[1])[0][0]

In [192]:
index_pos

1458

In [193]:
index_of_max

1458

In [200]:
str = filenames[index_of_max]

In [203]:
predicted_path.split('/')[1].replace('_',' ')

'Anushka Shetty'

# Detect Face

In [173]:
detector = MTCNN()
img_loc = 'sample/Ruquaiyah.jpeg'

In [174]:
to_face_img = cv2.imread(img_loc)

In [175]:
to_face_img.shape

(1280, 853, 3)

In [143]:
# 1.
for i in range(10):
    if to_face_img.shape[0]>800:
        to_face_img = cv2.resize(to_face_img, (int(to_face_img.shape[0]/2),to_face_img.shape[1]))
        if to_face_img.shape[1]>800:
            to_face_img = cv2.resize(to_face_img, (to_face_img.shape[0],int(to_face_img.shape[1]>800/2)))
    else:
        break

In [144]:
to_face_img.shape

(640, 426, 3)

In [176]:
# resizing of uploaded image
# 2.
for i in range(10):
    if to_face_img.shape[0]>800 and to_face_img.shape[1]>800:
        to_face_img = cv2.resize(to_face_img, (int((to_face_img.shape[1])/2),int((to_face_img.shape[0])/2)))
    else: 
        break

In [177]:
to_face_img.shape

(640, 426, 3)

In [178]:
result = detector.detect_faces(to_face_img)
result

[{'box': [162, 98, 117, 150],
  'confidence': np.float64(0.9984492063522339),
  'keypoints': {'nose': [np.int64(218), np.int64(187)],
   'mouth_right': [np.int64(245), np.int64(213)],
   'right_eye': [np.int64(249), np.int64(156)],
   'left_eye': [np.int64(191), np.int64(156)],
   'mouth_left': [np.int64(192), np.int64(211)]}}]

In [179]:
x,y,width,height = result[0]['box']

In [180]:
face = to_face_img[y:y+height,x:x+width]

In [181]:
cv2.imshow('output',face)
cv2.waitKey(0)

233

## Extract features

In [182]:
face1 = cv2.resize(face, (224,224))

In [121]:
type(face1)

numpy.ndarray

In [183]:
# img_loc = 'sample/ranbir_kapoor_dup.jpg'
sample_img = extract_features(face1)
print(sample_img)

[0.        0.        0.0944097 ... 0.        0.        0.       ]


In [198]:
%%time
%run test.py

56.9%
CPU times: user 5.41 s, sys: 0 ns, total: 5.41 s
Wall time: 10 s


In [2]:
!pip install bing-image-downloader

In [17]:
%run untitled.py

AttributeError: module 'web_image_downloader' has no attribute 'download_images'

In [21]:
!pip uninstall web_image_downloader -y

Found existing installation: web-image-downloader 1.0
Uninstalling web-image-downloader-1.0:
  Successfully uninstalled web-image-downloader-1.0


In [19]:
y

NameError: name 'y' is not defined